{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9773f7cf",
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import torch.nn.functional as F\n",
    "import numpy as np\n",
    "from collections import deque\n",
    "import pickle\n",
    "import os\n",
    "import traceback\n",
    "import time\n",
    "import gc\n",
    "\n",
    "# --- CONFIGURATION & DEVICE SETUP ---\n",
    "if torch.cuda.is_available():\n",
    "    device = torch.device('cuda')\n",
    "    print('CUDA is available. Using GPU.')\n",
    "else:\n",
    "    device = torch.device('cpu')\n",
    "    print('CUDA not available. Using CPU.')\n",
    "    \n",
    "\n",
    "# EU Regulatory Parameters (ETSI EN 300 220)\n",
    "EU_BAND_PARAMS = {\n",
    "    'L': {'freq': (865.0e6, 868.0e6), 'max_bw': 250e3, 'dc_limit': 0.01, 'erp': 14},\n",
    "    'M': {'freq': (868.0e6, 868.6e6), 'max_bw': 250e3, 'dc_limit': 0.01, 'erp': 14},\n",
    "    'P': {'freq': (869.4e6, 869.65e6), 'max_bw': 500e3, 'dc_limit': 0.1, 'erp': 27}\n",
    "}\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cda87469",
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- PHYSICS ENGINE UTILITIES ---\n",
    "\n",
    "# USE HANN WINDOW RAMP (FOR POWER AMPLIFIER) TO PREVENT SPECTRAL SPLATTER\n",
    "def apply_pa_ramp(frame, fs, ramp_time=10e-6):\n",
    "\n",
    "    ramp_samples = int(ramp_time * fs)\n",
    "    if ramp_samples * 2 >= len(frame):\n",
    "        window = torch.hann_window(len(frame), device=frame.device, dtype=torch.float32)\n",
    "        return frame * window\n",
    "    \n",
    "    ramp = torch.hann_window(ramp_samples * 2, device=frame.device, dtype=torch.float32)\n",
    "    frame[:ramp_samples] *= ramp[:ramp_samples]\n",
    "    frame[-ramp_samples:] *= ramp[ramp_samples:]\n",
    "    return frame\n",
    "\n",
    "# SINGLE TAP RAYLEIGH CHANNEL TO SIMULATE UNIFORM AMPLITUDE ATTENTUATION AND PHASE SHIFT ACROSS BAND\n",
    "def apply_flat_fading(signal):\n",
    "\n",
    "    if len(signal) < 1:\n",
    "        return signal\n",
    "    \n",
    "    # Generate Rayleigh fading coefficient: h = (h_real + j*h_imag) / sqrt(2)\n",
    "    h_real = torch.randn(1, device=device, dtype=torch.float32)\n",
    "    h_imag = torch.randn(1, device=device, dtype=torch.float32)\n",
    "    h = torch.complex(h_real, h_imag) / np.sqrt(2)\n",
    "    \n",
    "    return signal * h\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "15b0ab0f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- REGULATORY LOGIC ---\n",
    "\n",
    "# Determines non-compliant behavior (BW, OOB, ERP)\n",
    "def get_rogue_parameters(band_info, signal_type, p_rogue=0.10):\n",
    "\n",
    "    is_rogue = np.random.rand() < p_rogue\n",
    "    violations = {\n",
    "        'bw_violation': False,\n",
    "        'oob_violation': False,\n",
    "        'erp_violation': False,\n",
    "        'forced_bw': None,\n",
    "        'power_scale': 1.0,\n",
    "        'freq_offset': 0.0\n",
    "    }\n",
    "\n",
    "    if not is_rogue:\n",
    "        return violations\n",
    "\n",
    "    if 'max_bw' in band_info and signal_type in ['lora', 'mixture']:\n",
    "        if np.random.rand() < 0.5:\n",
    "            violations['forced_bw'] = 500e3\n",
    "            if violations['forced_bw'] > band_info['max_bw']:\n",
    "                violations['bw_violation'] = True\n",
    "\n",
    "    if np.random.rand() < 0.4:\n",
    "        violations['oob_violation'] = True\n",
    "        direction = np.random.choice([-1, 1])\n",
    "        violations['freq_offset'] = direction * 0.4\n",
    "\n",
    "    if np.random.rand() < 0.4:\n",
    "        violations['erp_violation'] = True\n",
    "        violations['power_scale'] = np.random.uniform(1.4, 2.0)\n",
    "\n",
    "    return violations\n",
    "\n",
    "\n",
    "\n",
    "# Ground truth generator for regulatory violations. Checks (BW, Symbol Rate, Duty Cycle, OOB, ERP)\n",
    "def check_regulatory_violations_strict(metadata, band_info, rogue_params):\n",
    "\n",
    "    violations = {}\n",
    "    max_signal_bw = 0\n",
    "    \n",
    "    if metadata.get('lora_params'):\n",
    "        max_signal_bw = max(max_signal_bw, metadata['lora_params']['BW'])\n",
    "        \n",
    "    if metadata.get('ieee_params'):\n",
    "        sym_rate = metadata['ieee_params']['symbol_rate']\n",
    "        \n",
    "        # Symbol rate guard band check (80% heuristic for FSK)\n",
    "        if sym_rate > band_info['max_bw'] * 0.8:\n",
    "            violations['bandwidth'] = f\"Symbol Rate {sym_rate/1e3:.1f}kHz > Guard Limit {band_info['max_bw']*0.8/1e3:.1f}kHz\"\n",
    "        max_signal_bw = max(max_signal_bw, sym_rate)\n",
    "\n",
    "    if max_signal_bw > band_info['max_bw']:\n",
    "        violations['bandwidth_limit'] = f\"BW {max_signal_bw/1e3:.1f}kHz > Limit {band_info['max_bw']/1e3:.1f}kHz\"\n",
    "\n",
    "    cf = metadata['center_frequency']\n",
    "    signal_bw = max_signal_bw if max_signal_bw > 0 else 125e3  # Default fallback\n",
    "    if (cf - signal_bw/2 < band_info['freq'][0]) or (cf + signal_bw/2 > band_info['freq'][1]):\n",
    "        violations['oob'] = \"Signal Spills Out-of-Band\"\n",
    "\n",
    "    if metadata.get('dc_violation', False):\n",
    "        violations['duty_cycle'] = \"DC Limit Exceeded\"\n",
    "\n",
    "    if rogue_params.get('erp_violation', False):\n",
    "        violations['erp'] = \"ERP Limit Exceeded\"\n",
    "\n",
    "    return violations\n",
    "\n",
    "\n",
    "# Determine signal type with persistence and realistic probabilities\n",
    "def select_lpwan_signal_type(tech_history):\n",
    "\n",
    "    # probabilities \n",
    "    LOR_P, IEE_P, MIX_P, NOI_P = 0.85, 0.05, 0.08, 0.02\n",
    "    \n",
    "    if not tech_history:\n",
    "        return np.random.choice(['lora', 'ieee', 'mixture', 'noise'], p=[LOR_P, IEE_P, MIX_P, NOI_P])\n",
    "    \n",
    "    # 75% persistence of previous technology\n",
    "    if np.random.rand() < 0.75:\n",
    "        return tech_history[-1]\n",
    "    \n",
    "    return np.random.choice(['lora', 'ieee', 'mixture', 'noise'], p=[LOR_P, IEE_P, MIX_P, NOI_P])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d61e0376",
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- WAVEFORM GENERATORS ---\n",
    "\n",
    "# LoRa signal generator with continuous phase tracking\n",
    "# Implements proper frequency wrapping and phase accumulation\n",
    "def generate_lora_signal(fs, frame_len, band_info, cf, prev_tech, last_phase, dc_violation, forced_bw=None):\n",
    "\n",
    "    if forced_bw is not None:\n",
    "        BW = forced_bw\n",
    "    elif dc_violation:\n",
    "        BW = 125e3\n",
    "    elif band_info['max_bw'] >= 500e3:\n",
    "        BW = np.random.choice([125e3, 250e3, 500e3])\n",
    "    else:\n",
    "        BW = np.random.choice([125e3, 250e3])\n",
    "    \n",
    "    SF = np.random.randint(7, 13)\n",
    "    if prev_tech == 'lora' and np.random.rand() < 0.8:\n",
    "        SF = min(12, max(7, SF + np.random.choice([-1, 0, 1])))\n",
    "    \n",
    "    symbol_duration = (2**SF) / BW\n",
    "    samples_per_symbol = int(symbol_duration * fs)\n",
    "    num_symbols = int(np.ceil(frame_len / samples_per_symbol))\n",
    "    \n",
    "    frame = torch.zeros(frame_len, dtype=torch.complex64, device=device)\n",
    "    \n",
    "    current_phase = last_phase if last_phase is not None else 0.0\n",
    "    freq_drift_rate = np.random.uniform(-20, 20)  # Hz/s\n",
    "\n",
    "    chirp_slope = BW / symbol_duration\n",
    "    \n",
    "    for i in range(num_symbols):\n",
    "        start = i * samples_per_symbol\n",
    "        end = min(start + samples_per_symbol, frame_len)\n",
    "        active = end - start\n",
    "        if active <= 0:\n",
    "            break\n",
    "        \n",
    "\n",
    "        k = np.random.randint(0, 2**SF)\n",
    "        freq_offset = k * BW / (2**SF)\n",
    "        \n",
    "        t_sym = torch.arange(active, device=device, dtype=torch.float32) / fs\n",
    "        \n",
    "        f_base = -BW/2 + chirp_slope * t_sym + freq_offset\n",
    "        f_wrapped = ((f_base + BW/2) % BW) - BW/2\n",
    "        phase_inc = 2 * np.pi * f_wrapped / fs\n",
    "        sym_phase = torch.cumsum(phase_inc, dim=0)\n",
    "        drift = 2 * np.pi * freq_drift_rate * (t_sym**2) / 2\n",
    "        total_phase = current_phase + sym_phase + drift\n",
    "        frame[start:end] = torch.exp(1j * total_phase)\n",
    "        current_phase = total_phase[-1].item() % (2 * np.pi)\n",
    "    \n",
    "    metadata = {\n",
    "        'SF': SF,\n",
    "        'BW': BW,\n",
    "        'symbol_duration': symbol_duration,\n",
    "        'freq_drift_rate': freq_drift_rate,\n",
    "        'last_phase': current_phase\n",
    "    }\n",
    "    \n",
    "    return frame, metadata\n",
    "\n",
    "\n",
    "\n",
    "# --- IEEE 802.15.4g GFSK signal generator with proper Gaussian filtering. ---\n",
    "# --- Symbol rate constrained to bandwidth limits. ---\n",
    "def generate_ieee_signal(fs, frame_len, band_info, cf, prev_tech, last_phase, dc_violation):\n",
    "    allowed_bw = band_info['max_bw']\n",
    "    \n",
    "    # Conservative rates to fit within bandwidth (Carson's Rule: BW ≈ 2*(Δf + R))\n",
    "    if allowed_bw >= 500e3:\n",
    "        possible_rates = [50e3, 100e3, 150e3, 200e3]\n",
    "    elif allowed_bw >= 250e3:\n",
    "        possible_rates = [50e3, 100e3]\n",
    "    else:\n",
    "        possible_rates = [50e3]\n",
    "    \n",
    "    if dc_violation:\n",
    "        possible_rates = [50e3]\n",
    "    \n",
    "    symbol_rate = np.random.choice(possible_rates)\n",
    "    mod_index = np.random.choice([0.5, 1.0])\n",
    "    BT = 0.5  # Bandwidth-time product\n",
    "    samples_per_symbol = max(1, int(fs / symbol_rate))\n",
    "    freq_dev = (mod_index * symbol_rate) / 2\n",
    "    num_symbols = max(1, frame_len // samples_per_symbol)    \n",
    "    symbols = torch.randint(0, 2, (num_symbols,), device=device, dtype=torch.float32) * 2 - 1\n",
    "    \n",
    "    # Create Gaussian pulse shaping filter\n",
    "    t_pulse = torch.arange(-3 * samples_per_symbol, 3 * samples_per_symbol + 1,\n",
    "                           device=device, dtype=torch.float32) / fs\n",
    "    gaussian_std = np.sqrt(np.log(2)) / (2 * np.pi * BT * symbol_rate)\n",
    "    gauss_pulse = torch.exp(-0.5 * (t_pulse / gaussian_std)**2)\n",
    "    gauss_pulse = gauss_pulse / gauss_pulse.sum()\n",
    "\n",
    "    symbols_upsampled = torch.repeat_interleave(symbols, samples_per_symbol)\n",
    "\n",
    "    if len(symbols_upsampled) < frame_len:\n",
    "        pad = torch.zeros(frame_len - len(symbols_upsampled), device=device, dtype=torch.float32)\n",
    "        symbols_upsampled = torch.cat((symbols_upsampled, pad))\n",
    "    else:\n",
    "        symbols_upsampled = symbols_upsampled[:frame_len]\n",
    "    \n",
    "    symbols_3d = symbols_upsampled.unsqueeze(0).unsqueeze(0)\n",
    "    kernel_3d = gauss_pulse.unsqueeze(0).unsqueeze(0)\n",
    "    \n",
    "    filtered_3d = F.conv1d(symbols_3d, kernel_3d, padding=len(gauss_pulse)//2)\n",
    "    filtered = filtered_3d.squeeze()[:frame_len]    \n",
    "    freq_waveform = freq_dev * filtered    \n",
    "    phase = 2 * np.pi * torch.cumsum(freq_waveform, dim=0) / fs\n",
    "    t = torch.arange(frame_len, device=device, dtype=torch.float32) / fs\n",
    "    freq_drift_rate = np.random.uniform(-5, 5)\n",
    "    phase += 2 * np.pi * freq_drift_rate * t**2 / 2\n",
    "    \n",
    "\n",
    "    if last_phase is not None:\n",
    "        phase += last_phase\n",
    "    frame = torch.exp(1j * phase)\n",
    "    current_phase = phase[-1].item() % (2 * np.pi)\n",
    "    \n",
    "    metadata = {\n",
    "        'symbol_rate': symbol_rate,\n",
    "        'modulation': 'GFSK',\n",
    "        'mod_index': mod_index,\n",
    "        'BT_product': BT,\n",
    "        'freq_dev': freq_dev,\n",
    "        'freq_drift_rate': freq_drift_rate,\n",
    "        'last_phase': current_phase\n",
    "    }\n",
    "    \n",
    "    return frame, metadata\n",
    "\n",
    "\n",
    "# Creates realistic coexistence scenarios between LoRa and IEEE signals\n",
    "# Models power ratio, frequency separation, and timing offset.\n",
    "def apply_coexistence_constraints(lora, ieee, lora_meta, ieee_meta, fs):\n",
    "\n",
    "    min_len = min(len(lora), len(ieee))\n",
    "    if min_len == 0:\n",
    "        return ieee, {}\n",
    "    \n",
    "    lora, ieee = lora[:min_len], ieee[:min_len]    \n",
    "    power_ratio_db = np.random.uniform(5, 15)\n",
    "    scale_factor = torch.sqrt(torch.tensor(10**(power_ratio_db/10), device=device, dtype=torch.float32))\n",
    "    \n",
    "    if np.random.rand() < 0.7:\n",
    "        ieee = ieee / scale_factor\n",
    "        power_ratio = power_ratio_db\n",
    "    else:\n",
    "        lora = lora / scale_factor\n",
    "        power_ratio = -power_ratio_db\n",
    "    \n",
    "    if np.random.rand() < 0.3:\n",
    "        freq_sep = np.random.uniform(-50e3, 50e3)\n",
    "        interf_type = 'co-channel'\n",
    "    else:\n",
    "        freq_sep = np.random.choice([-1, 1]) * np.random.uniform(100e3, 300e3)\n",
    "        interf_type = 'adjacent-channel'\n",
    "    \n",
    "    t = torch.arange(min_len, device=device, dtype=torch.float32) / fs\n",
    "    ieee_shifted = ieee * torch.exp(1j * 2 * np.pi * freq_sep * t)\n",
    "    \n",
    "    max_offset = int(0.1 * fs)\n",
    "    offset = np.random.randint(-max_offset, max_offset) if max_offset > 0 else 0\n",
    "    ieee_shifted = torch.roll(ieee_shifted, offset)\n",
    "    mixed = lora + ieee_shifted\n",
    "    \n",
    "    coex_metadata = {\n",
    "        'power_ratio_db': power_ratio,\n",
    "        'freq_separation': freq_sep,\n",
    "        'timing_offset': offset,\n",
    "        'interference_type': interf_type\n",
    "    }\n",
    "    \n",
    "    return mixed, coex_metadata"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0a7930d3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- FRAME GENERATION CONTROLLER ---\n",
    "\n",
    "# Main controller for generating LPWAN signal frames.\n",
    "# Handles LoRa, IEEE, mixture, and noise types with regulatory compliance.\n",
    "def generate_lpwan_spectrum_frame(fs, signal_type, band_id, band_info, dc_violation,\n",
    "                                   prev_tech, symbol_memory, frame_len):\n",
    "\n",
    "    if signal_type == 'noise':\n",
    "        meta = {\n",
    "            'signal_type': 'noise',\n",
    "            'regulatory_violations': {},\n",
    "            'center_frequency': np.mean(band_info['freq']),\n",
    "            'is_rogue': False,\n",
    "            'rogue_details': {},\n",
    "            'lora_params': None,\n",
    "            'ieee_params': None,\n",
    "            'coex_params': None\n",
    "        }\n",
    "        return None, meta, symbol_memory\n",
    "\n",
    "    rogue_params = get_rogue_parameters(band_info, signal_type, p_rogue=0.50)    \n",
    "    f_low, f_high = band_info['freq']\n",
    "    safe_margin = 0.1e6\n",
    "    center_freq = np.random.uniform(f_low + safe_margin, f_high - safe_margin)\n",
    "    \n",
    "    if rogue_params['oob_violation']:\n",
    "       \n",
    "        bw_est = rogue_params.get('forced_bw') or 125e3\n",
    "        \n",
    "        if rogue_params['freq_offset'] > 0:\n",
    "            center_freq = f_high - (bw_est * 0.1)\n",
    "        else:\n",
    "            center_freq = f_low + (bw_est * 0.1)\n",
    "\n",
    "    # Initialize metadata\n",
    "    metadata = {\n",
    "        'signal_type': signal_type,\n",
    "        'band_id': band_id,\n",
    "        'center_frequency': center_freq,\n",
    "        'dc_violation': dc_violation,\n",
    "        'is_rogue': any(rogue_params[k] for k in ['bw_violation', 'oob_violation', 'erp_violation']),\n",
    "        'rogue_details': rogue_params,\n",
    "        'regulatory_violations': {},\n",
    "        'lora_params': None,\n",
    "        'ieee_params': None,\n",
    "        'coex_params': None\n",
    "    }\n",
    "    \n",
    "    if rogue_params['erp_violation']:\n",
    "        metadata['erp_violation'] = True\n",
    "    \n",
    "    frame = torch.zeros(frame_len, dtype=torch.complex64, device=device)\n",
    "    forced_bw = rogue_params.get('forced_bw', None)\n",
    "    lora_signal_ref = None\n",
    "    \n",
    "    # LoRa generation\n",
    "    if signal_type in ['lora', 'mixture']:\n",
    "        l_frame, l_meta = generate_lora_signal(\n",
    "            fs, frame_len, band_info, center_freq, prev_tech,\n",
    "            symbol_memory.get('lora'), dc_violation, forced_bw\n",
    "        )\n",
    "        if signal_type == 'lora':\n",
    "            frame += l_frame\n",
    "        metadata['lora_params'] = l_meta\n",
    "        symbol_memory['lora'] = l_meta['last_phase']\n",
    "        lora_signal_ref = l_frame\n",
    "\n",
    "    # IEEE generation\n",
    "    if signal_type in ['ieee', 'mixture']:\n",
    "        i_frame, i_meta = generate_ieee_signal(\n",
    "            fs, frame_len, band_info, center_freq, prev_tech,\n",
    "            symbol_memory.get('ieee'), dc_violation\n",
    "        )\n",
    "        if signal_type == 'ieee':\n",
    "            frame += i_frame\n",
    "        metadata['ieee_params'] = i_meta\n",
    "        symbol_memory['ieee'] = i_meta['last_phase']\n",
    "        \n",
    "        # Mixture handling\n",
    "        if signal_type == 'mixture' and lora_signal_ref is not None:\n",
    "            mixed, mix_meta = apply_coexistence_constraints(\n",
    "                lora_signal_ref, i_frame, l_meta, i_meta, fs\n",
    "            )\n",
    "            frame = mixed\n",
    "            metadata['coex_params'] = mix_meta\n",
    "\n",
    "    metadata['regulatory_violations'] = check_regulatory_violations_strict(\n",
    "        metadata, band_info, rogue_params\n",
    "    )\n",
    "    \n",
    "    return frame, metadata, symbol_memory"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "94b791bb",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# --- MAIN DATASET GENERATOR ---\n",
    "\n",
    "# Generates a complete LPWAN spectrum sequence with overlapping snapshots.\n",
    "# Implements proper SNR control via caached buffer technique.\n",
    "def generate_lpwan_spectrum_dataset_with_snapshots(\n",
    "    fs=1e6, seq_len=1.0, min_frames=8, max_frames=20, region='EU',\n",
    "    snr_db=10, snapshot_len_sec=0.1, overlap_sec=0.05, gap_scale=0.02, jitter_max=0.02\n",
    "):\n",
    "    seq_samples = int(seq_len * fs)    \n",
    "    sequence = torch.zeros(seq_samples, dtype=torch.complex64, device=device)\n",
    "    \n",
    "    # initilize cached buffer\n",
    "    clean_sequence = torch.zeros(seq_samples, dtype=torch.complex64, device=device)\n",
    "    \n",
    "    full_metadata = {\n",
    "        'region': region,\n",
    "        'fs': fs,\n",
    "        'snr_db': snr_db,\n",
    "        'sub_band': None,\n",
    "        'frames': [],\n",
    "        'temporal_features': [],\n",
    "        'dc_violations': 0,\n",
    "        'erp_violations': 0,\n",
    "        'total_tx_time': 0.0,\n",
    "        'noise_power': None,\n",
    "        'signal_power': None\n",
    "    }\n",
    "\n",
    "    band_probs = {'M': 0.7, 'P': 0.25, 'L': 0.05}\n",
    "    band_id = np.random.choice(list(band_probs.keys()), p=list(band_probs.values()))\n",
    "    full_metadata['sub_band'] = band_id\n",
    "    band_info = EU_BAND_PARAMS[band_id]\n",
    "\n",
    "    limit = band_info['dc_limit']\n",
    "    r = np.random.rand()\n",
    "    if r < 0.7:\n",
    "        dc_accumulator = np.random.uniform(0, 0.5 * limit)\n",
    "    elif r < 0.9:\n",
    "        dc_accumulator = np.random.uniform(0.5 * limit, 0.9 * limit)\n",
    "    else:\n",
    "        dc_accumulator = np.random.uniform(0.9 * limit, 1.1 * limit)\n",
    "\n",
    "    current_sample = 0\n",
    "    tech_history = deque(maxlen=5)\n",
    "    symbol_memory = {'lora': None, 'ieee': None}\n",
    "    frame_count = 0\n",
    "    prev_tech = None\n",
    "\n",
    "    while current_sample < seq_samples and frame_count < max_frames:\n",
    "        gap = int(np.random.exponential(gap_scale * fs))\n",
    "        current_sample += gap\n",
    "        if current_sample >= seq_samples:\n",
    "            break\n",
    "        \n",
    "        max_len = min(int(0.5 * fs), seq_samples - current_sample)\n",
    "        min_len = int(0.01 * fs)\n",
    "        if max_len < min_len:\n",
    "            break\n",
    "        \n",
    "        frame_len = np.random.randint(min_len, max_len + 1)\n",
    "        frame_duration = frame_len / fs\n",
    "        dc_accumulator += frame_duration / 3600\n",
    "        dc_violation = dc_accumulator > limit\n",
    "        if dc_violation:\n",
    "            full_metadata['dc_violations'] += 1\n",
    "        \n",
    "        violate_dc_intent = np.random.rand() < 0.10\n",
    "        if (frame_count >= min_frames) and dc_violation and not violate_dc_intent:\n",
    "            continue\n",
    "\n",
    "        signal_type = select_lpwan_signal_type(tech_history)        \n",
    "        if signal_type == 'noise':\n",
    "            dc_accumulator -= frame_duration / 3600\n",
    "            dc_accumulator = max(0.0, dc_accumulator)  # Prevent negative\n",
    "            if dc_violation:\n",
    "                full_metadata['dc_violations'] -= 1\n",
    "            dc_violation = dc_accumulator > limit\n",
    "\n",
    "        tech_history.append(signal_type)\n",
    "\n",
    "        frame, frame_meta, symbol_memory = generate_lpwan_spectrum_frame(\n",
    "            fs, signal_type, band_id, band_info, dc_violation,\n",
    "            prev_tech, symbol_memory, frame_len\n",
    "        )\n",
    "        \n",
    "        end_idx = min(current_sample + frame_len, seq_samples)\n",
    "\n",
    "        if frame is None:\n",
    "            frame_meta['boundary'] = {'start': current_sample, 'end': end_idx}\n",
    "            frame_meta['frame_duration'] = frame_duration\n",
    "            full_metadata['frames'].append(frame_meta)\n",
    "            current_sample = end_idx\n",
    "            prev_tech = 'noise'\n",
    "        else:\n",
    "            p_frame = torch.mean(torch.abs(frame)**2)\n",
    "            if p_frame > 0:\n",
    "                frame = frame / torch.sqrt(p_frame)\n",
    "            \n",
    "            if frame_meta.get('rogue_details', {}).get('erp_violation'):\n",
    "                frame = frame * frame_meta['rogue_details']['power_scale']\n",
    "                full_metadata['erp_violations'] += 1\n",
    "            \n",
    "            faded_frame = apply_flat_fading(frame)\n",
    "            ramped_frame = apply_pa_ramp(faded_frame, fs)\n",
    "            actual_len = end_idx - current_sample\n",
    "            if len(ramped_frame) > actual_len:\n",
    "                ramped_frame = ramped_frame[:actual_len]\n",
    "            \n",
    "            sequence[current_sample:end_idx] += ramped_frame            \n",
    "            clean_sequence[current_sample:end_idx] += ramped_frame\n",
    "            full_metadata['total_tx_time'] += actual_len / fs\n",
    "            frame_meta['boundary'] = {'start': current_sample, 'end': end_idx}\n",
    "            frame_meta['frame_duration'] = actual_len / fs\n",
    "            full_metadata['frames'].append(frame_meta)\n",
    "            \n",
    "            current_sample = end_idx\n",
    "            prev_tech = signal_type\n",
    "        \n",
    "        frame_count += 1\n",
    "\n",
    "    snr_linear = 10**(snr_db / 10)\n",
    "    noise_power = 1.0 / snr_linear\n",
    "    noise_std = torch.sqrt(torch.tensor(noise_power / 2.0, device=device, dtype=torch.float32))\n",
    "    \n",
    "    noise_real = torch.randn(seq_samples, device=device, dtype=torch.float32) * noise_std\n",
    "    noise_imag = torch.randn(seq_samples, device=device, dtype=torch.float32) * noise_std\n",
    "    noise = torch.complex(noise_real, noise_imag)\n",
    "    \n",
    "    sequence += noise\n",
    "    \n",
    "    full_metadata['signal_power'] = 1.0\n",
    "    full_metadata['noise_power'] = float(noise_power)\n",
    "    full_metadata['duty_cycle'] = full_metadata['total_tx_time'] / seq_len\n",
    "\n",
    "    snapshot_len_samples = int(snapshot_len_sec * fs)\n",
    "    overlap_samples = int(overlap_sec * fs)\n",
    "    step_samples = snapshot_len_samples - overlap_samples\n",
    "    \n",
    "    max_jitter = min(int(jitter_max * fs), step_samples // 2)\n",
    "    first_start = np.random.randint(0, max_jitter + 1) if max_jitter > 0 else 0\n",
    "\n",
    "    snapshots = []\n",
    "    snapshot_metadata = []\n",
    "    start_sample = first_start\n",
    "    snap_idx = 0\n",
    "\n",
    "    while start_sample + snapshot_len_samples <= seq_samples:\n",
    "        end_sample = start_sample + snapshot_len_samples\n",
    "        \n",
    "        snap = sequence[start_sample:end_sample]\n",
    "        \n",
    "        clean_snap = clean_sequence[start_sample:end_sample]\n",
    "        clean_power_val = float(torch.mean(torch.abs(clean_snap)**2).item())\n",
    "        \n",
    "        contained = []\n",
    "        for i, fm in enumerate(full_metadata['frames']):\n",
    "            b = fm['boundary']\n",
    "            if b['start'] < end_sample and b['end'] > start_sample:\n",
    "                ov_start = max(b['start'], start_sample)\n",
    "                ov_end = min(b['end'], end_sample)\n",
    "                contained.append({\n",
    "                    'frame_idx': i,\n",
    "                    'type': fm['signal_type'],\n",
    "                    'overlap': [ov_start, ov_end],\n",
    "                    'overlap_ratio': (ov_end - ov_start) / max(1, b['end'] - b['start'])\n",
    "                })\n",
    "        \n",
    "        snapshots.append(snap)\n",
    "        snapshot_metadata.append({\n",
    "            'index': snap_idx,\n",
    "            'start_sample': start_sample,\n",
    "            'contained_frames': contained,\n",
    "            'band_id': band_id,\n",
    "            'snr_db': snr_db,\n",
    "            'clean_power': clean_power_val\n",
    "        })\n",
    "        \n",
    "        start_sample += step_samples\n",
    "        snap_idx += 1\n",
    "\n",
    "    if snapshots:\n",
    "        snapshots = torch.stack(snapshots)\n",
    "    else:\n",
    "        snapshots = torch.empty((0, snapshot_len_samples), dtype=torch.complex64, device=device)\n",
    "    \n",
    "    return snapshots, snapshot_metadata, full_metadata\n",
    "\n",
    "# Generate labels for snapshots based on contained frames (noise, lora, ieee, mixture-cochannel, mixture-adjacent).\n",
    "def label_snapshots(snapshot_metadata, full_metadata):\n",
    "\n",
    "    labels = []\n",
    "    \n",
    "    for snap_meta in snapshot_metadata:\n",
    "        contained = snap_meta['contained_frames']\n",
    "        \n",
    "        if not contained:\n",
    "            labels.append(\"noise\")\n",
    "            continue\n",
    "        \n",
    "        types = set(c['type'] for c in contained)        \n",
    "        has_lora = 'lora' in types or 'mixture' in types\n",
    "        has_ieee = 'ieee' in types or 'mixture' in types\n",
    "        is_mixture_frame = any(c['type'] == 'mixture' for c in contained)\n",
    "        \n",
    "        if is_mixture_frame:\n",
    "            mix_frame_idx = next(c['frame_idx'] for c in contained if c['type'] == 'mixture')\n",
    "            coex_params = full_metadata['frames'][mix_frame_idx].get('coex_params', {})\n",
    "            interf_type = coex_params.get('interference_type', 'co-channel')\n",
    "            \n",
    "            if 'adjacent' in interf_type:\n",
    "                labels.append('mixture-adjacent')\n",
    "            else:\n",
    "                labels.append('mixture-cochannel')\n",
    "            continue\n",
    "        \n",
    "        if len(types) == 1:\n",
    "            labels.append(list(types)[0])\n",
    "        else:\n",
    "            durations = {}\n",
    "            for c in contained:\n",
    "                dur = c['overlap'][1] - c['overlap'][0]\n",
    "                durations[c['type']] = durations.get(c['type'], 0) + dur\n",
    "            labels.append(max(durations, key=durations.get))\n",
    "    \n",
    "    return labels\n",
    "\n",
    "\n",
    "# Captures Rogues, SNR, AND Coexistence Ratios.\n",
    "def extract_detailed_metadata(snap_meta, full_metadata, snapshot, fs):\n",
    "\n",
    "    meta = {\n",
    "        'label': snap_meta['label'],\n",
    "        'snr_db': snap_meta['snr_db'],\n",
    "        'lora_params': None,\n",
    "        'ieee_params': None,\n",
    "        'coex_params': None, # <--- NEW FIELD\n",
    "        'signal_power': snap_meta.get('clean_power', 0.0),\n",
    "        'rogue_details': {},\n",
    "        'band_id': snap_meta.get('band_id', 'Unknown')\n",
    "    }\n",
    "    \n",
    "    has_dc_violation = False\n",
    "    has_rogue_violation = False\n",
    "    \n",
    "    for c in snap_meta['contained_frames']:\n",
    "        f_meta = full_metadata['frames'][c['frame_idx']]\n",
    "        \n",
    "        if f_meta.get('dc_violation'): has_dc_violation = True\n",
    "        if f_meta.get('regulatory_violations'): \n",
    "            has_rogue_violation = True\n",
    "            if f_meta.get('rogue_details'):\n",
    "                meta['rogue_details'] = f_meta['rogue_details']\n",
    "        \n",
    "        if c['type'] == 'lora':\n",
    "            meta['lora_params'] = f_meta['lora_params']\n",
    "        elif c['type'] == 'ieee':\n",
    "            meta['ieee_params'] = f_meta['ieee_params']\n",
    "        elif c['type'] == 'mixture':\n",
    "            meta['lora_params'] = f_meta.get('lora_params')\n",
    "            meta['ieee_params'] = f_meta.get('ieee_params')\n",
    "            \n",
    "            # For Near-Far Ratio and Interference Type\n",
    "            if f_meta.get('coex_params'):\n",
    "                meta['coex_params'] = f_meta['coex_params']\n",
    "\n",
    "    meta['duty_cycle_violation'] = has_dc_violation\n",
    "    meta['regulatory_violations'] = has_rogue_violation\n",
    "\n",
    "    if snap_meta['contained_frames']:\n",
    "        idx = snap_meta['contained_frames'][0]['frame_idx']\n",
    "        meta['center_frequency'] = full_metadata['frames'][idx]['center_frequency']\n",
    "    else:\n",
    "        meta['center_frequency'] = 868.0e6\n",
    "\n",
    "    return meta"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fa0b1cdd",
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- VERIFICATION & TESTING ---\n",
    "\n",
    "# Verify SNR for each snapshot using the cached buffer and \n",
    "# returns dictionary mapping snapshot index to measured SNR.\n",
    "def verify_snr_post_generation(snapshots, snapshot_metadata, full_metadata):\n",
    "    snr_map = {}\n",
    "    global_noise_power = full_metadata.get('noise_power', None)\n",
    "\n",
    "    for meta in snapshot_metadata:\n",
    "        has_active_frames = any(c['type'] != 'noise' for c in meta['contained_frames'])\n",
    "        if not has_active_frames:\n",
    "            continue\n",
    "\n",
    "        if 'clean_power' in meta and global_noise_power is not None:\n",
    "            P_signal = meta['clean_power']\n",
    "            P_noise = global_noise_power\n",
    "            \n",
    "            if P_signal > 1e-12 and P_noise > 1e-12:\n",
    "                snr = 10 * np.log10(P_signal / P_noise)\n",
    "                snr_map[meta['index']] = snr\n",
    "    \n",
    "    return snr_map\n",
    "\n",
    "# To obtain equal representation of all signal classes\n",
    "# returns dictionary mapping snapshot index to measured SNR.\n",
    "def generate_balanced_dataset(target_per_class=200, save_path=\"lamp_mmv_dataset.pkl\"):\n",
    "\n",
    "    all_snapshots = []\n",
    "    all_metadata = []\n",
    "    \n",
    "    class_targets = {\n",
    "        'noise': target_per_class,\n",
    "        'lora': target_per_class,\n",
    "        'ieee': target_per_class,\n",
    "        'mixture-adjacent': target_per_class,\n",
    "        'mixture-cochannel': target_per_class\n",
    "    }\n",
    "    counts = {k: 0 for k in class_targets}\n",
    "    \n",
    "    print(f\"Generating balanced dataset: {target_per_class} samples per class\")\n",
    "    start_time = time.time()\n",
    "    \n",
    "    iteration = 0\n",
    "    max_iterations = 10000\n",
    "    \n",
    "    while not all(counts[k] >= target_per_class for k in counts) and iteration < max_iterations:\n",
    "        iteration += 1\n",
    "        \n",
    "        try:\n",
    "            snaps, snap_metas, full_meta = generate_lpwan_spectrum_dataset_with_snapshots(\n",
    "                seq_len=1.0,\n",
    "                snr_db=10\n",
    "            )\n",
    "            \n",
    "            if len(snaps) == 0:\n",
    "                continue\n",
    "            \n",
    "            labels = label_snapshots(snap_metas, full_meta)\n",
    "            \n",
    "            for i, (snap, sm, lbl) in enumerate(zip(snaps, snap_metas, labels)):\n",
    "                \n",
    "                if 'mixture' in lbl:\n",
    "                    if 'co' in lbl.lower():\n",
    "                        lbl = 'mixture-cochannel'\n",
    "                    else:\n",
    "                        lbl = 'mixture-adjacent'\n",
    "                \n",
    "                sm['label'] = lbl\n",
    "                \n",
    "                if lbl in counts and counts[lbl] < class_targets[lbl]:\n",
    "                    \n",
    "                    has_active_frames = any(c['type'] != 'noise' for c in sm['contained_frames'])\n",
    "                    \n",
    "                    P_noise = full_meta.get('noise_power')\n",
    "                    P_signal = sm.get('clean_power')\n",
    "\n",
    "                    if has_active_frames and P_noise is not None and P_signal is not None:\n",
    "                        if P_signal > 1e-12 and P_noise > 1e-12:\n",
    "                            sm['verified_snr'] = 10 * np.log10(P_signal / P_noise)\n",
    "\n",
    "                    detailed = extract_detailed_metadata(sm, full_meta, snap, 1e6)\n",
    "                    \n",
    "                    if 'verified_snr' in sm:\n",
    "                        detailed['verified_snr'] = sm['verified_snr']\n",
    "\n",
    "                    all_snapshots.append(snap.cpu().numpy())\n",
    "                    all_metadata.append(detailed)\n",
    "                    counts[lbl] += 1\n",
    "            \n",
    "            del snaps, snap_metas, full_meta\n",
    "            if torch.cuda.is_available():\n",
    "                torch.cuda.empty_cache()\n",
    "            \n",
    "            if iteration % 20 == 0:\n",
    "                gc.collect()\n",
    "\n",
    "        except Exception as e:\n",
    "            print(f\"Error in iteration {iteration}: {e}\")\n",
    "            traceback.print_exc()\n",
    "            continue\n",
    "        \n",
    "        if iteration % 50 == 0:\n",
    "            elapsed = time.time() - start_time\n",
    "            total = sum(counts.values())\n",
    "            target_total = len(counts) * target_per_class\n",
    "            pct = 100 * total / target_total if target_total > 0 else 0\n",
    "            rate = iteration / elapsed if elapsed > 0 else 0\n",
    "            eta_sec = (max_iterations - iteration) / rate if rate > 0 else 0\n",
    "            \n",
    "            print(f\"[{pct:.1f}%] Iter {iteration}/{max_iterations} | \"\n",
    "                  f\"Counts: {counts} | \"\n",
    "                  f\"Rate: {rate:.1f} it/s | \"\n",
    "                  f\"ETA: {eta_sec/60:.1f}m\")\n",
    "\n",
    "    # Save dataset\n",
    "    dataset = {\n",
    "        'snapshots': all_snapshots,\n",
    "        'metadata': all_metadata,\n",
    "        'counts': counts,\n",
    "        'generation_time': time.time() - start_time\n",
    "    }\n",
    "    \n",
    "    with open(save_path, 'wb') as f:\n",
    "        pickle.dump(dataset, f)\n",
    "    \n",
    "    print(f\"\\nDataset generation complete!\")\n",
    "    print(f\"Total time: {dataset['generation_time']/60:.1f} minutes\")\n",
    "    print(f\"Final counts: {counts}\")\n",
    "    print(f\"Saved to: {save_path}\")\n",
    "    \n",
    "    return dataset\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e79e80c7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- MAIN EXECUTION ---\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    np.random.seed(42)\n",
    "    torch.manual_seed(42)\n",
    "    generate_balanced_dataset(\n",
    "        target_per_class=1000,\n",
    "        save_path=\"lamp_mmv_robust10dbFthird1.pkl\"\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0aebbbf0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c7c6a144",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4cde58f3",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ce8be8b4",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "efc8a16f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ad130e37",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "30e1b3c9",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4cb9d8fc",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "715dfbd4",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4f398dc4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
